# Maintainer: jakeroggenbuck <jakeroggenbuck2@gmail.com
# Maintainer: cameron <cameron.bannasch@gmail.com>
# Maintainer: shuzhengz <treez.zhang@gmail.com>
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=autoclockspeed-bin
pkgver=0.1.11
pkgrel=1
pkgdesc="A utility to check stats about your CPU, and auto regulate clock speeds to help with either performance or battery life."
url="https://github.com/JakeRoggenbuck/auto-clock-speed"
license=("MIT OR MPL-2.0")
arch=("x86_64")
provides=("autoclockspeed")
conflicts=("autoclockspeed")
source=("https://github.com/JakeRoggenbuck/auto-clock-speed/releases/download/v$pkgver/autoclockspeed-$pkgver-x86_64.tar.gz")
sha256sums=("08d3f45df0e61466c93d28a3190f62f7ba60461b92304bf2dc5b8a94226ce06d")

package() {
    install -Dm755 acs -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE-MIT "$pkgdir/usr/share/licenses/$pkgname/LICENSE-MIT"
}
